// MERN/Frontend/src/page/auth/Register.jsx
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuthContext } from "../../hooks/useAuthContext";
import { api } from "../../utils/api";

const Register = () => {
    const [user, setUser] = useState({ email: "", password: "" });
    const [errors, setErrors] = useState({});
    const { dispatch } = useAuthContext();
    const navigate = useNavigate();
    const handleChange = (e) => {
        const { name, value } = e.target;
        setUser((prev) => ({ ...prev, [name]: value }));
    };

    const validate = () => {
        let err = {};
        if (!user.email) {
            err.email = "Email is required";
        }
        if (!user.password) {
            err.password = "Password is required";
        }
        setErrors(err);
        return Object.keys(err).length === 0;
    };
    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            if (!validate()) return;
            const responce = await api.post("/user/register", {
                email: user.email,
                password: user.password,
            });
            if (responce.data) {
                console.log(responce.data);
                localStorage.setItem("user", JSON.stringify(responce.data));
                dispatch({ type: "LOGIN", payload: responce });
                setUser({ email: "", password: "" });
                navigate("/");
            }
        } catch (error) {
            console.error(error);
            setErrors((prev) => ({
                ...prev,
                other: error.response.data.error,
            }));
        }
    };
    return (
        <div className="flex items-center justify-center w-full min-h-screen">
            <div className="flex flex-col items-center justify-center w-1/4 bg-white p-4 rounded-md shadow-md">
                <h1 className="text-2xl font-bold mb-4">Register</h1>
                <form
                    className="flex flex-col gap-4 w-full"
                    onSubmit={handleSubmit}
                >
                    <div className="flex flex-col gap-2">
                        <input
                            type="email"
                            name="email"
                            value={user.email}
                            onChange={handleChange}
                            placeholder="Email"
                            className="border border-gray-300 rounded-md p-2"
                        />
                        <p className="text-red-500 leading-tight text-sm">
                            {errors.email}
                        </p>
                    </div>
                    <div className="flex flex-col gap-2">
                        <input
                            type="password"
                            name="password"
                            value={user.password}
                            onChange={handleChange}
                            placeholder="Password"
                            className="border border-gray-300 rounded-md p-2"
                        />
                        <p className="text-red-500 leading-tight text-sm">
                            {errors.password}
                        </p>
                    </div>
                    <p className="text-red-500 leading-tight text-sm">
                        {errors.other}
                    </p>
                    <button
                        type="submit"
                        className="bg-blue-500 text-white py-2 rounded-md"
                    >
                        Register
                    </button>
                </form>
                <p className="text-gray-500 leading-tight mt-4 text-sm">
                    
                    Have an account?
                    <Link to="/login" className="text-blue-500">
                        Login
                    </Link>
                </p>
            </div>
        </div>
    );
};

export default Register;

// blog/src/page/auth/Register.vue
<script setup>
import api from "@/utils/api";
import axios from "axios";
import { Field, Form, ErrorMessage } from "vee-validate";
import { ref } from "vue";
import { useRouter } from "vue-router";
import * as yup from "yup";
const router = useRouter();
const register = ref({});
const redirect = () => {
  router.push({ name: "login" });
};
const onSubmit = async () => {
  try {
    await api.post("/register", {
      name: register.value.name,
      email: register.value.email,
      password: register.value.password,
      password_confirmation: register.value.confirmpassword,
    });
    redirect();
  } catch (error) {
    console.error(error);
  }
};
const schema = yup.object({
  email: yup.string().email().required(),
  name: yup.string().required(),
  password: yup.string().min(6).required(),
  confirmpassword: yup
    .string()
    .min(6)
    .required()
    .oneOf([yup.ref("password")]),
});
</script>
<template>
  <div class="min-h-screen flex items-center justify-center p-4">
    <div
      class="w-full max-w-md rounded-2xl shadow-xl p-8 border dark:bg-neutral-800 border-gray-100"
    >
      <h2 class="text-3xl font-bold text-gray-900 dark:text-gray-50 mb-1 text-center">
        Register
      </h2>
      <p class="text-gray-500 dark:text-gray-300 text-center mb-8">Sign UP to account</p>
      <Form @submit="onSubmit" :validation-schema="schema" class="space-y-6">
        <div class="flex flex-col gap-1">
          <label for="name" class="text-sm font-medium text-gray-700 dark:text-gray-300"
            >Name</label
          >
          <Field
            name="name"
            v-model="register.name"
            type="name"
            placeholder="name"
            class="px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition"
          />
          <ErrorMessage name="name" class="text-sm text-red-600" />
        </div>
        <div class="flex flex-col gap-1">
          <label for="email" class="text-sm font-medium text-gray-700 dark:text-gray-300"
            >Email</label
          >
          <Field
            name="email"
            v-model="register.email"
            type="email"
            placeholder="you@example.com"
            class="px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition"
          />
          <ErrorMessage name="email" class="text-sm text-red-600" />
        </div>
        <div class="flex flex-col gap-1">
          <label for="password" class="text-sm font-medium text-gray-700 dark:text-gray-300"
            >password</label
          >
          <Field
            name="password"
            v-model="register.password"
            type="password"
            placeholder="••••••••"
            class="px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition"
          />
          <ErrorMessage name="password" class="text-sm text-red-600" />
        </div>
        <div class="flex flex-col gap-1">
          <label for="confirmpassword" class="text-sm font-medium text-gray-700 dark:text-gray-300"
            >Confirm Password</label
          >
          <Field
            name="confirmpassword"
            v-model="register.confirmpassword"
            type="confirmpassword"
            placeholder="••••••••"
            class="px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition"
          />
          <ErrorMessage name="confirmpassword" class="text-sm text-red-600" />
        </div>

        <button
          type="submit"
          class="w-full bg-blue-600 text-white py-3 rounded-lg font-semibold hover:bg-blue-700 transition duration-200 shadow-md hover:shadow-lg"
        >
          Sign UP
        </button>

        <div class="text-center text-sm text-gray-600 dark:text-gray-300 mt-6">
          Already an user?
          <span
            class="text-blue-600 hover:underline cursor-pointer font-medium"
            @click="router.push({ name: 'login' })"
          >
            login
          </span>
        </div>
      </Form>
    </div>
  </div>
</template>
